name: 'Duplication Detecting Action'
description: 'Scan every existing issue and inform the issuer if any duplication detected'
branding:
  icon: 'alert-circle'
  color: 'blue'
inputs:
  issue_num:  # issue number
    description: 'Number of the new issue'
    required: true
  issue_contents: # issue contents
    description: 'Contents of the new issue'
    required: true
  repository_path_name: # repository name
    description: 'Path name of the repository'
    required: true
  rapid_key: # RapidAPI's key
    description: 'Key for the RapidAPI'
    required: true
  repo_key: # GitHub access token
    description: 'Acees token for GitHub'
    required: true
  threshold: # Threshold similarity
    description: 'Threshold similarity to use for the detection'
    default: "NaN"
    required: false
    type: number
outputs:
  dup_num: # possible duplicated issue's number
    description: 'The number of detected issue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.issue_num }}
    - ${{ inputs.issue_contents }}
    - ${{ inputs.repository_path_name }}
    - ${{ inputs.rapid_key }}
    - ${{ inputs.repo_key }}